name: kumihan
description: "Flutter canvas widget for vertical Japanese book rendering."
version: 0.0.2
repository: "https://github.com/h-sumiya/kumihan"

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.6
  markdown: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: WebFontGothic
      fonts:
        - asset: fonts/ipaexg.ttf
    - family: WebFontMonoGothic
      fonts:
        - asset: fonts/ipag-mona.ttf
    - family: WebFontMincho
      fonts:
        - asset: fonts/ipaexm.ttf
    - family: WebFontMonoMincho
      fonts:
        - asset: fonts/ipam-mona.ttf
